# Generated by Django 3.0.3 on 2020-04-04 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='example_files')),
                ('description', models.CharField(max_length=100)),
                ('example_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Example data',
                'verbose_name_plural': 'Example data',
            },
        ),
        migrations.CreateModel(
            name='Job_Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(default=0)),
                ('input_file', models.FileField(editable=False, upload_to='input_files')),
                ('output_file', models.FileField(blank=True, upload_to='output_files')),
                ('n_spectra', models.IntegerField(default=1, verbose_name='Number of spectra')),
                ('ageMin', models.FloatField(default=None)),
                ('ageMax', models.FloatField(default=None)),
                ('Zmin', models.FloatField(default=None)),
                ('Zmax', models.FloatField(default=None)),
                ('flux_units', models.FloatField(default=None)),
                ('model', models.CharField(max_length=16)),
                ('imf', models.CharField(max_length=15)),
                ('wave_medium', models.CharField(max_length=10)),
                ('downgrade_models', models.BooleanField(default=None)),
                ('width_masking', models.FloatField(default=None)),
                ('emission_lines', models.CharField(max_length=50)),
                ('submitted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(default='preprocessing', max_length=20)),
            ],
            options={
                'verbose_name': 'Job Submission',
            },
        ),
        migrations.CreateModel(
            name='SED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_file', models.FileField(blank=True, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.IntegerField(default=0)),
            ],
        ),
    ]
