# Generated by Django 3.0.3 on 2020-04-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_submission',
            name='Zmax',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job_submission',
            name='Zmin',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job_submission',
            name='ageMax',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job_submission',
            name='ageMin',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job_submission',
            name='downgrade_models',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job_submission',
            name='emission_lines',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job_submission',
            name='flux_units',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job_submission',
            name='imf',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job_submission',
            name='model',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='job_submission',
            name='wave_medium',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job_submission',
            name='width_masking',
            field=models.FloatField(default=None, null=True),
        ),
    ]
