# Generated by Django 3.0.3 on 2020-04-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefly', '0002_auto_20200404_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_submission',
            name='ageMax',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
