# Generated by Django 3.0.3 on 2020-02-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefly', '0002_auto_20200210_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireflyTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Firefly',
        ),
    ]
