# Generated by Django 3.0.3 on 2020-04-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefly', '0003_auto_20200413_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='example_data',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='example_data',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
