# Generated by Django 3.0.3 on 2020-04-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefly', '0004_auto_20200423_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example_data',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
