# Generated by Django 3.0.3 on 2020-02-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefly', '0004_sed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireflyResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sed',
            name='results_id',
            field=models.IntegerField(default=0),
        ),
    ]
