# Generated by Django 3.0.3 on 2020-02-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefly', '0006_fireflyresults_results_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sed',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
