# Generated by Django 3.0.3 on 2020-02-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefly', '0007_auto_20200226_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireflyresults',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
