# Generated by Django 3.0.3 on 2020-02-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firefly', '0009_auto_20200226_2311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FireflyResults',
            new_name='Job_Submission',
        ),
    ]
