# Generated by Django 3.0.3 on 2020-02-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firefly', '0011_auto_20200227_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_submission',
            old_name='output_file',
            new_name='input_file',
        ),
    ]
