# Generated by Django 3.0.3 on 2020-02-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firefly', '0012_auto_20200227_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example_data',
            old_name='file',
            new_name='output_file',
        ),
        migrations.RenameField(
            model_name='job_submission',
            old_name='file',
            new_name='output_file',
        ),
        migrations.RenameField(
            model_name='sed',
            old_name='file',
            new_name='output_file',
        ),
    ]
