# Generated by Django 3.0.3 on 2020-02-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firefly', '0013_auto_20200227_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_submission',
            name='uploaded_at',
        ),
    ]
