# Generated by Django 3.0.3 on 2020-02-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firefly', '0014_remove_job_submission_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example_data',
            old_name='output_file',
            new_name='input_file',
        ),
        migrations.AddField(
            model_name='example_data',
            name='example_id',
            field=models.IntegerField(default=0),
        ),
    ]
