# Generated by Django 3.0.3 on 2020-02-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firefly', '0015_auto_20200229_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example_data',
            options={'verbose_name': 'Example data', 'verbose_name_plural': 'Example data'},
        ),
    ]
