"""
Django settings for firefly_website project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'SECRET_KEY.txt')) as f:
    SECRET_KEY = f.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

BACKGROUND_TASK_RUN_ASYNC = False
MAX_ATTEMPTS = 1

# Application definition

INSTALLED_APPS = [
    'firefly.apps.FireflyConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'background_task'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'firefly_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'firefly_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL  = '/media/'

"""
TEMP_FILES    = os.path.join(MEDIA_ROOT, 'temp_files')
INPUT_FILES   = os.path.join(MEDIA_ROOT, 'input_files')
OUTPUT_FILES  = os.path.join(MEDIA_ROOT, 'output_files')
EXAMPLE_FILES = os.path.join(MEDIA_ROOT, 'example_files')

#Create the directories if they do not exist.
if os.path.isdir(TEMP_FILES) is False:
    os.mkdir(TEMP_FILES)

if os.path.isdir(INPUT_FILES) is False:
    os.mkdir(INPUT_FILES)

if os.path.isdir(OUTPUT_FILES) is False:
    os.mkdir(OUTPUT_FILES)

if os.path.isdir(EXAMPLE_FILES) is False:
    os.mkdir(EXAMPLE_FILES)
"""

JOB_SUBIMISSIONS_ROOT = os.path.join(MEDIA_ROOT, 'job_submissions')
if os.path.isdir(JOB_SUBIMISSIONS_ROOT) is False:
    os.mkdir(JOB_SUBIMISSIONS_ROOT)

EXAMPLE_FILES = os.path.join(MEDIA_ROOT, 'example_files')
if os.path.isdir(EXAMPLE_FILES) is False:
    os.mkdir(EXAMPLE_FILES)